# app.py for Hugging Face Spaces
#
# This script adapts the English Poetry Scansion Tool for deployment with Gradio.
# It uses the definitive weighted scoring engine and provides a rich, color-coded
# HTML output for the analysis.
#
# REQUIRED FILES in the HF Space:
# 1. app.py (this file)
# 2. requirements.txt
# 3. english_phonetic_dict.pkl (generated by the final `create_dictionary_pkl.py` script)

import gradio as gr
import pickle
import re
import os

# --- Core Scansion Logic (v6.0 Engine) ---
# This class is copied directly from our final Tkinter version.
class EnglishScansion:
    def __init__(self, dict_path):
        if not os.path.exists(dict_path):
            raise FileNotFoundError(f"CRITICAL ERROR: The dictionary file '{dict_path}' was not found in the Hugging Face Space repository.")
        
        with open(dict_path, 'rb') as f:
            self.pronunciation_dict = pickle.load(f)

        self.METERS = {'Iambic': '01', 'Trochaic': '10', 'Anapestic': '001', 'Dactylic': '100', 'Amphibrach': '010'}
        self.VOWELS = "aeiouyAEIOUY"
        self.ACCENT_MAP = {'a': 'á', 'e': 'é', 'i': 'í', 'o': 'ó', 'u': 'ú', 'y': 'ý',
                           'A': 'Á', 'E': 'É', 'I': 'Í', 'O': 'Ó', 'U': 'Ú', 'Y': 'Ý'}
        self.VOWEL_SOUNDS = re.compile(r'[A-Z]{2,3}[0-9]')
        self.FUNCTION_WORDS = {
            'a', 'an', 'the', 'and', 'but', 'or', 'for', 'nor', 'on', 'at', 'to', 'from',
            'by', 'with', 'in', 'of', 'is', 'am', 'are', 'was', 'were', 'be', 'being',
            'been', 'have', 'has', 'had', 'do', 'does', 'did', 'will', 'would', 'shall',
            'should', 'can', 'could', 'may', 'might', 'must', 'as', 'if', 'so', 'my', 'your',
            'his', 'her', 'its', 'our', 'their', 'me', 'you', 'him', 'her', 'it', 'us', 'them'
        }

    def get_word_data(self, word):
        lookup_word = word.lower().strip(".,;:!?()\"'")
        if not lookup_word or lookup_word not in self.pronunciation_dict:
            return None, f"<{lookup_word}>", 0, None

        arpabet_list, ipa_raw = self.pronunciation_dict[lookup_word][0]
        stress_pattern, syllable_count = "", 0

        for phoneme in arpabet_list:
            if self.VOWEL_SOUNDS.match(phoneme):
                syllable_count += 1
                stress_pattern += '1' if phoneme.endswith('1') or phoneme.endswith('2') else '0'
        
        return stress_pattern, ' '.join(arpabet_list), syllable_count, ipa_raw

    def analyze_line(self, line):
        words = re.findall(r"[\w']+|[.,!?;:]+", line)
        lexical_stress_pattern, word_map = "", []
        
        for word in words:
            if re.match(r"[\w']+", word):
                pattern, _, syllables, _ = self.get_word_data(word)
                if pattern is not None:
                    lexical_stress_pattern += pattern
                    word_map.extend([word.lower()] * syllables)

        line_syllables = len(lexical_stress_pattern)
        if line_syllables == 0:
            return {"original": line, "meter": "Unknown", "score": 1.0, "syllables": 0, "final_stress_pattern": ""}

        scores = {}
        for name, pattern in self.METERS.items():
            template = (pattern * (line_syllables // len(pattern) + 1))[:line_syllables]
            mismatch_score = 0
            for i in range(line_syllables):
                if lexical_stress_pattern[i] != template[i]:
                    weight = 0.5 if word_map[i] in self.FUNCTION_WORDS else 1.0
                    mismatch_score += weight
            scores[name] = mismatch_score / line_syllables
        
        best_meter_name = min(scores, key=scores.get)
        best_meter_score = scores[best_meter_name]

        winning_meter_pattern = self.METERS[best_meter_name]
        final_stress_pattern = (winning_meter_pattern * (line_syllables // len(winning_meter_pattern) + 1))[:line_syllables]

        foot_len = len(winning_meter_pattern)
        num_feet = round(line_syllables / foot_len) if foot_len > 0 else 0
        foot_map = {0:"0-foot", 1:"monometer", 2:"dimeter", 3:"trimeter", 4:"tetrameter", 5:"pentameter", 6:"hexameter"}
        meter_desc = f"{best_meter_name} {foot_map.get(num_feet, f'{num_feet}-foot')}"

        return {"original": line, "meter": meter_desc, "score": best_meter_score, "syllables": line_syllables, "final_stress_pattern": final_stress_pattern}

    def format_line(self, line, analysis_result, format_type):
        words = re.findall(r"[\w']+|[^\w']+", line)
        output_parts = []
        if format_type == 'arpabet' or format_type == 'ipa':
            for word in words:
                if re.match(r"[\w']+", word):
                    _, arpabet, _, ipa = self.get_word_data(word)
                    output_parts.append(ipa if format_type == 'ipa' and ipa else f"[{arpabet}]")
                else:
                    output_parts.append(word)
            return " ".join(output_parts)

        final_stress = analysis_result['final_stress_pattern']
        syllable_cursor = 0
        for word in words:
            if not re.match(r"[\w']+", word):
                output_parts.append(word)
                continue
            lexical_pattern, _, num_syllables, _ = self.get_word_data(word)
            if lexical_pattern is None:
                output_parts.append(f"<{word}>")
                continue
            word_stress_segment = final_stress[syllable_cursor : syllable_cursor + num_syllables]
            if format_type == 'plus':
                output_parts.append(f"+{word}" if '1' in word_stress_segment else word)
            elif format_type == 'accent':
                temp_word = list(word)
                vowel_groups = list(re.finditer(r'[aeiouy]+', word, re.IGNORECASE))
                for i, stress_char in enumerate(word_stress_segment):
                    if stress_char == '1' and i < len(vowel_groups):
                        vowel_match = vowel_groups[i]
                        pos = vowel_match.start()
                        char_to_stress = temp_word[pos]
                        temp_word[pos] = self.ACCENT_MAP.get(char_to_stress, char_to_stress)
                output_parts.append("".join(temp_word))
            syllable_cursor += num_syllables
        return " ".join(output_parts).replace(" ,", ",").replace(" .", ".").strip()

# --- Gradio Conversion Logic ---

# Define colors for HTML output
COLORS = {
    'vowel': "#9370DB",          # Purple
    'stressed_vowel': "#FF474C", # Red
    'consonant': "#FFC700",       # Yellow
    'punctuation': "#32CD32",    # Green
    'info': "#FFFFFF",           # White
    'separator': "#555555",
    'header': "#FFFFFF"
}

def render_html_line(text):
    """Converts a line of text into a color-coded HTML string."""
    accented_vowels = "áéíóúýÁÉÍÓÚÝ"
    html_string = ""
    for char in text:
        char_html = char
        if char in accented_vowels:
            style = f'color:{COLORS["stressed_vowel"]}; font-weight:bold;'
        elif char in "aeiouyAEIOUY":
            style = f'color:{COLORS["vowel"]};'
        elif char.isalpha():
            style = f'color:{COLORS["consonant"]};'
        elif char in "<>":
            style = f'color:{COLORS["separator"]};'
        elif char in ".,;:!?'\"":
            style = f'color:{COLORS["punctuation"]};'
        elif char == '+':
            style = f'color:{COLORS["stressed_vowel"]}; font-weight:bold;'
        else:
            style = f'color:{COLORS["info"]};'
        
        # Escape HTML characters and wrap in span
        escaped_char = {'<': '&lt;', '>': '&gt;', '&': '&amp;'}.get(char, char)
        html_string += f'<span style="{style}">{escaped_char}</span>'
    return html_string

# Main function for Gradio to call
def analyze_poem(poem_text):
    scanner = EnglishScansion(dict_path="english_phonetic_dict.pkl")
    if not poem_text.strip():
        return "<p style='color:grey;'>Please enter some poetry to analyze.</p>"

    # Start building the HTML output with styles
    html_output = f"""
    <style>
        .output-container {{
            background-color: black;
            color: white;
            padding: 20px;
            border-radius: 10px;
            font-family: Menlo, Monaco, 'Courier New', monospace;
            font-size: 14px;
            line-height: 1.6;
            white-space: pre-wrap; /* Allows wrapping and preserves whitespace */
        }}
        .output-container h2 {{
            text-align: center;
            text-decoration: underline;
            font-size: 16px;
            margin-top: 2em;
            margin-bottom: 1em;
        }}
        .output-container hr {{
            border-color: {COLORS['separator']};
            border-style: solid;
        }}
    </style>
    <div class="output-container">
    """
    
    accented_poem_lines = []
    ipa_poem_lines = []

    for line in poem_text.strip().split('\n'):
        if not line.strip():
            html_output += "<br>"
            continue

        analysis = scanner.analyze_line(line)
        
        plus_line = scanner.format_line(line, analysis, 'plus')
        accent_line = scanner.format_line(line, analysis, 'accent')
        arpabet_line = scanner.format_line(line, analysis, 'arpabet')
        ipa_line = scanner.format_line(line, analysis, 'ipa')
        
        accented_poem_lines.append(accent_line)
        ipa_poem_lines.append(ipa_line)

        # Render line-by-line analysis
        html_output += render_html_line(plus_line) + "<br>"
        html_output += render_html_line(accent_line) + "<br>"
        html_output += f"<span style='color:{COLORS['info']}'>{arpabet_line}</span><br>"
        html_output += f"<span style='color:{COLORS['info']}'>Meter: {analysis['meter']} | Syllables: {analysis['syllables']} | Mismatch Score: {analysis['score']:.2f}</span><br>"
        html_output += "<hr>"

    # Render summaries
    html_output += "<h2>Stressed Poem Summary</h2>"
    for line in accented_poem_lines:
        html_output += render_html_line(line) + "<br>"
        
    html_output += "<h2>IPA Phonetic Transcription</h2>"
    for line in ipa_poem_lines:
        html_output += f"<span style='color:{COLORS['info']}'>{line}</span><br>"

    html_output += "</div>"
    return html_output

# --- Gradio Interface Definition ---

TITLE = "English Poetry Scansion Tool"
DESCRIPTION = """
A tool for analyzing English syllabo-tonic poetry, based on the work of Ilya Koziev (see https://github.com/Koziev/EnglishPoetryScansion).
This app performs scansion by finding the best-fit poetic meter for each line, highlighting stresses,
and providing phonetic transcriptions. It uses a weighted scoring system to measure each line's correspondence apropos the closest-matched out of several relatively widespread disyllabic or trisyllabic metrical foot patterns. 
"""
EXAMPLE_POEM = "But I will ignite\nIn your eyes a fire\nNow I give you strength\nNow I give you power"

iface = gr.Interface(
    fn=analyze_poem,
    inputs=gr.Textbox(lines=8, label="Poem Input", placeholder="Enter your poem here...", value=EXAMPLE_POEM),
    outputs=gr.HTML(label="Analysis Output"),
    title=TITLE,
    description=DESCRIPTION,
    allow_flagging="never"
)

if __name__ == "__main__":
    iface.launch()
